// tslint:disable
/**
 * OE API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { HttpMethods, QueryConfig, ResponseBody, ResponseText } from 'redux-query';
import * as runtime from '../runtime';

import {
    Product,
    ProductFromJSON,
    ProductToJSON,
} from '../models';

export interface ProductsCreateRequest {
    data: Product;
}


/**
 */
function productsCreateRaw<T>(requestParameters: ProductsCreateRequest, requestConfig: runtime.TypedQueryConfig<T, Product> = {}): QueryConfig<T> {
    if (requestParameters.data === null || requestParameters.data === undefined) {
        throw new runtime.RequiredError('data','Required parameter requestParameters.data was null or undefined when calling productsCreate.');
    }

    let queryParameters = null;


    const headerParameters = {};

    headerParameters['Content-Type'] = 'application/json';


    const { meta = {} } = requestConfig;

    meta.authType = ['oauth', []];
    const config: QueryConfig<T> = {
        url: `/products`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'POST',
            headers: headerParameters,
        },
        body: queryParameters || ProductToJSON(requestParameters.data),
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(ProductFromJSON(body), text);
    }

    return config;
}

/**
*/
export function productsCreate<T>(requestParameters: ProductsCreateRequest, requestConfig?: runtime.TypedQueryConfig<T, Product>): QueryConfig<T> {
    return productsCreateRaw(requestParameters, requestConfig);
}

/**
 */
function productsListRaw<T>( requestConfig: runtime.TypedQueryConfig<T, Array<Product>> = {}): QueryConfig<T> {
    let queryParameters = null;


    const headerParameters = {};


    const { meta = {} } = requestConfig;

    meta.authType = ['oauth', []];
    const config: QueryConfig<T> = {
        url: `/products`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'GET',
            headers: headerParameters,
        },
        body: queryParameters,
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(body.map(ProductFromJSON), text);
    }

    return config;
}

/**
*/
export function productsList<T>( requestConfig?: runtime.TypedQueryConfig<T, Array<Product>>): QueryConfig<T> {
    return productsListRaw( requestConfig);
}

