// tslint:disable
/**
 * OE API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { HttpMethods, QueryConfig, ResponseBody, ResponseText } from 'redux-query';
import * as runtime from '../runtime';

import {
    Category,
    CategoryFromJSON,
    CategoryToJSON,
} from '../models';

export interface ProductscategoriesCreateRequest {
    data: Category;
}


/**
 */
function productscategoriesCreateRaw<T>(requestParameters: ProductscategoriesCreateRequest, requestConfig: runtime.TypedQueryConfig<T, Category> = {}): QueryConfig<T> {
    if (requestParameters.data === null || requestParameters.data === undefined) {
        throw new runtime.RequiredError('data','Required parameter requestParameters.data was null or undefined when calling productscategoriesCreate.');
    }

    let queryParameters = null;


    const headerParameters = {};

    headerParameters['Content-Type'] = 'application/json';


    const { meta = {} } = requestConfig;

    meta.authType = ['oauth', []];
    const config: QueryConfig<T> = {
        url: `/productscategories`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'POST',
            headers: headerParameters,
        },
        body: queryParameters || CategoryToJSON(requestParameters.data),
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(CategoryFromJSON(body), text);
    }

    return config;
}

/**
*/
export function productscategoriesCreate<T>(requestParameters: ProductscategoriesCreateRequest, requestConfig?: runtime.TypedQueryConfig<T, Category>): QueryConfig<T> {
    return productscategoriesCreateRaw(requestParameters, requestConfig);
}

/**
 */
function productscategoriesListRaw<T>( requestConfig: runtime.TypedQueryConfig<T, Array<Category>> = {}): QueryConfig<T> {
    let queryParameters = null;


    const headerParameters = {};


    const { meta = {} } = requestConfig;

    meta.authType = ['oauth', []];
    const config: QueryConfig<T> = {
        url: `/productscategories`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'GET',
            headers: headerParameters,
        },
        body: queryParameters,
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(body.map(CategoryFromJSON), text);
    }

    return config;
}

/**
*/
export function productscategoriesList<T>( requestConfig?: runtime.TypedQueryConfig<T, Array<Category>>): QueryConfig<T> {
    return productscategoriesListRaw( requestConfig);
}

