// tslint:disable
/**
 * OE API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { HttpMethods, QueryConfig, ResponseBody, ResponseText } from 'redux-query';
import * as runtime from '../runtime';

import {
    LoginSeller,
    LoginSellerFromJSON,
    LoginSellerToJSON,
} from '../models';

export interface SellersloginCreateRequest {
    data: LoginSeller;
}


/**
 */
function sellersloginCreateRaw<T>(requestParameters: SellersloginCreateRequest, requestConfig: runtime.TypedQueryConfig<T, LoginSeller> = {}): QueryConfig<T> {
    if (requestParameters.data === null || requestParameters.data === undefined) {
        throw new runtime.RequiredError('data','Required parameter requestParameters.data was null or undefined when calling sellersloginCreate.');
    }

    let queryParameters = null;


    const headerParameters = {};

    headerParameters['Content-Type'] = 'application/json';


    const { meta = {} } = requestConfig;

    meta.authType = ['oauth', []];
    const config: QueryConfig<T> = {
        url: `/sellerslogin`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'POST',
            headers: headerParameters,
        },
        body: queryParameters || LoginSellerToJSON(requestParameters.data),
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(LoginSellerFromJSON(body), text);
    }

    return config;
}

/**
*/
export function sellersloginCreate<T>(requestParameters: SellersloginCreateRequest, requestConfig?: runtime.TypedQueryConfig<T, LoginSeller>): QueryConfig<T> {
    return sellersloginCreateRaw(requestParameters, requestConfig);
}

