// tslint:disable
/**
 * OE API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Address
 */
export interface Address  {
    /**
     * 
     * @type {number}
     * @memberof Address
     */
    readonly id?: number;
    /**
     * The name prefix. For example, Mr, Mrs, Ms, Dr, etc.
     * @type {string}
     * @memberof Address
     */
    prefix?: string;
    /**
     * The name for the address.
     * @type {string}
     * @memberof Address
     */
    name: string;
    /**
     * The name suffix. For example, Jr, Sr, etc.
     * @type {string}
     * @memberof Address
     */
    suffix?: string;
    /**
     * Any other text to display along with the address. This could be department names (for companies) or titles (for people).
     * @type {string}
     * @memberof Address
     */
    nameExt?: string;
    /**
     * The company name for the address.
     * @type {string}
     * @memberof Address
     */
    companyName?: string;
    /**
     * The business tax number.
     * @type {string}
     * @memberof Address
     */
    taxNumber?: string;
    /**
     * The primary phone number for the address.
     * @type {string}
     * @memberof Address
     */
    phone?: string;
    /**
     * The primary email for the address.
     * @type {string}
     * @memberof Address
     */
    email?: string;
    /**
     * The street address.
     * @type {string}
     * @memberof Address
     */
    street: string;
    /**
     * An additional street address line.
     * @type {string}
     * @memberof Address
     */
    street2?: string;
    /**
     * Any additional street address line.
     * @type {string}
     * @memberof Address
     */
    street3?: string;
    /**
     * The address postal/zip code.
     * @type {string}
     * @memberof Address
     */
    postalCode?: string;
    /**
     * The address city.
     * @type {string}
     * @memberof Address
     */
    city: string;
    /**
     * The address region, province, or state.
     * @type {string}
     * @memberof Address
     */
    regionCode?: string;
    /**
     * The address region, province, or state.
     * @type {string}
     * @memberof Address
     */
    region?: string;
    /**
     * The address country.
     * @type {string}
     * @memberof Address
     */
    country?: AddressCountryEnum;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    longitude?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    latitude?: string;
}

export function AddressFromJSON(json: any): Address {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'prefix': !exists(json, 'prefix') ? undefined : json['prefix'],
        'name': json['name'],
        'suffix': !exists(json, 'suffix') ? undefined : json['suffix'],
        'nameExt': !exists(json, 'name_ext') ? undefined : json['name_ext'],
        'companyName': !exists(json, 'company_name') ? undefined : json['company_name'],
        'taxNumber': !exists(json, 'tax_number') ? undefined : json['tax_number'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'street': json['street'],
        'street2': !exists(json, 'street2') ? undefined : json['street2'],
        'street3': !exists(json, 'street3') ? undefined : json['street3'],
        'postalCode': !exists(json, 'postal_code') ? undefined : json['postal_code'],
        'city': json['city'],
        'regionCode': !exists(json, 'region_code') ? undefined : json['region_code'],
        'region': !exists(json, 'region') ? undefined : json['region'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'longitude': !exists(json, 'longitude') ? undefined : json['longitude'],
        'latitude': !exists(json, 'latitude') ? undefined : json['latitude'],
    };
}

export function AddressToJSON(value?: Address): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'prefix': value.prefix,
        'name': value.name,
        'suffix': value.suffix,
        'name_ext': value.nameExt,
        'company_name': value.companyName,
        'tax_number': value.taxNumber,
        'phone': value.phone,
        'email': value.email,
        'street': value.street,
        'street2': value.street2,
        'street3': value.street3,
        'postal_code': value.postalCode,
        'city': value.city,
        'region_code': value.regionCode,
        'region': value.region,
        'country': value.country,
        'longitude': value.longitude,
        'latitude': value.latitude,
    };
}

/**
* @export
* @enum {string}
*/
export enum AddressCountryEnum {
    AF = 'AF',
    AX = 'AX',
    AL = 'AL',
    DZ = 'DZ',
    AS = 'AS',
    AD = 'AD',
    AO = 'AO',
    AI = 'AI',
    AQ = 'AQ',
    AG = 'AG',
    AR = 'AR',
    AM = 'AM',
    AW = 'AW',
    AU = 'AU',
    AT = 'AT',
    AZ = 'AZ',
    BS = 'BS',
    BH = 'BH',
    BD = 'BD',
    BB = 'BB',
    BY = 'BY',
    BE = 'BE',
    BZ = 'BZ',
    BJ = 'BJ',
    BM = 'BM',
    BT = 'BT',
    BO = 'BO',
    BQ = 'BQ',
    BA = 'BA',
    BW = 'BW',
    BV = 'BV',
    BR = 'BR',
    IO = 'IO',
    BN = 'BN',
    BG = 'BG',
    BF = 'BF',
    BI = 'BI',
    CV = 'CV',
    KH = 'KH',
    CM = 'CM',
    CA = 'CA',
    KY = 'KY',
    CF = 'CF',
    TD = 'TD',
    CL = 'CL',
    CN = 'CN',
    CX = 'CX',
    CC = 'CC',
    CO = 'CO',
    KM = 'KM',
    CG = 'CG',
    CD = 'CD',
    CK = 'CK',
    CR = 'CR',
    CI = 'CI',
    HR = 'HR',
    CU = 'CU',
    CW = 'CW',
    CY = 'CY',
    CZ = 'CZ',
    DK = 'DK',
    DJ = 'DJ',
    DM = 'DM',
    DO = 'DO',
    EC = 'EC',
    EG = 'EG',
    SV = 'SV',
    GQ = 'GQ',
    ER = 'ER',
    EE = 'EE',
    SZ = 'SZ',
    ET = 'ET',
    FK = 'FK',
    FO = 'FO',
    FJ = 'FJ',
    FI = 'FI',
    FR = 'FR',
    GF = 'GF',
    PF = 'PF',
    TF = 'TF',
    GA = 'GA',
    GM = 'GM',
    GE = 'GE',
    DE = 'DE',
    GH = 'GH',
    GI = 'GI',
    GR = 'GR',
    GL = 'GL',
    GD = 'GD',
    GP = 'GP',
    GU = 'GU',
    GT = 'GT',
    GG = 'GG',
    GN = 'GN',
    GW = 'GW',
    GY = 'GY',
    HT = 'HT',
    HM = 'HM',
    VA = 'VA',
    HN = 'HN',
    HK = 'HK',
    HU = 'HU',
    IS = 'IS',
    IN = 'IN',
    ID = 'ID',
    IR = 'IR',
    IQ = 'IQ',
    IE = 'IE',
    IM = 'IM',
    IL = 'IL',
    IT = 'IT',
    JM = 'JM',
    JP = 'JP',
    JE = 'JE',
    JO = 'JO',
    KZ = 'KZ',
    KE = 'KE',
    KI = 'KI',
    KW = 'KW',
    KG = 'KG',
    LA = 'LA',
    LV = 'LV',
    LB = 'LB',
    LS = 'LS',
    LR = 'LR',
    LY = 'LY',
    LI = 'LI',
    LT = 'LT',
    LU = 'LU',
    MO = 'MO',
    MG = 'MG',
    MW = 'MW',
    MY = 'MY',
    MV = 'MV',
    ML = 'ML',
    MT = 'MT',
    MH = 'MH',
    MQ = 'MQ',
    MR = 'MR',
    MU = 'MU',
    YT = 'YT',
    MX = 'MX',
    FM = 'FM',
    MD = 'MD',
    MC = 'MC',
    MN = 'MN',
    ME = 'ME',
    MS = 'MS',
    MA = 'MA',
    MZ = 'MZ',
    MM = 'MM',
    NA = 'NA',
    NR = 'NR',
    NP = 'NP',
    NL = 'NL',
    NC = 'NC',
    NZ = 'NZ',
    NI = 'NI',
    NE = 'NE',
    NG = 'NG',
    NU = 'NU',
    NF = 'NF',
    KP = 'KP',
    MK = 'MK',
    MP = 'MP',
    OM = 'OM',
    PK = 'PK',
    PW = 'PW',
    PS = 'PS',
    PA = 'PA',
    PG = 'PG',
    PY = 'PY',
    PE = 'PE',
    PH = 'PH',
    PN = 'PN',
    PL = 'PL',
    PT = 'PT',
    PR = 'PR',
    QA = 'QA',
    RE = 'RE',
    RO = 'RO',
    RU = 'RU',
    RW = 'RW',
    BL = 'BL',
    SH = 'SH',
    KN = 'KN',
    LC = 'LC',
    MF = 'MF',
    PM = 'PM',
    VC = 'VC',
    WS = 'WS',
    SM = 'SM',
    ST = 'ST',
    SA = 'SA',
    SN = 'SN',
    RS = 'RS',
    SC = 'SC',
    SL = 'SL',
    SG = 'SG',
    SX = 'SX',
    SK = 'SK',
    SI = 'SI',
    SB = 'SB',
    SO = 'SO',
    ZA = 'ZA',
    GS = 'GS',
    KR = 'KR',
    SS = 'SS',
    ES = 'ES',
    LK = 'LK',
    SD = 'SD',
    SR = 'SR',
    SJ = 'SJ',
    SE = 'SE',
    CH = 'CH',
    SY = 'SY',
    TW = 'TW',
    TJ = 'TJ',
    TZ = 'TZ',
    TH = 'TH',
    TL = 'TL',
    TG = 'TG',
    TK = 'TK',
    TO = 'TO',
    TT = 'TT',
    TN = 'TN',
    TR = 'TR',
    TM = 'TM',
    TC = 'TC',
    TV = 'TV',
    UG = 'UG',
    UA = 'UA',
    AE = 'AE',
    GB = 'GB',
    UM = 'UM',
    US = 'US',
    UY = 'UY',
    UZ = 'UZ',
    VU = 'VU',
    VE = 'VE',
    VN = 'VN',
    VG = 'VG',
    VI = 'VI',
    WF = 'WF',
    EH = 'EH',
    YE = 'YE',
    ZM = 'ZM',
    ZW = 'ZW'
}


