// tslint:disable
/**
 * OE API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Category
 */
export interface Category  {
    /**
     * 
     * @type {number}
     * @memberof Category
     */
    readonly id?: number;
    /**
     * Do not change this value if you are not sure what you are doing.
     * @type {string}
     * @memberof Category
     */
    readonly identifier?: string;
    /**
     * Here you can choose whether or not you want the category to be visible in your store.
     * @type {number}
     * @memberof Category
     */
    status?: number;
    /**
     * You can set the order of categories in your store numerically.
     * @type {number}
     * @memberof Category
     */
    ordering?: number;
    /**
     * You can choose to limit who sees your category based on whether they are logged in or if they are  part of a customer group.
     * @type {number}
     * @memberof Category
     */
    visibility?: number;
    /**
     * 
     * @type {number}
     * @memberof Category
     */
    readonly lft?: number;
    /**
     * 
     * @type {number}
     * @memberof Category
     */
    readonly rght?: number;
    /**
     * 
     * @type {number}
     * @memberof Category
     */
    readonly treeId?: number;
    /**
     * 
     * @type {number}
     * @memberof Category
     */
    readonly level?: number;
    /**
     * If your category is a sub-category of another category, you can link them here.
     * @type {number}
     * @memberof Category
     */
    parent?: number;
    /**
     * Category image. Will be shown at theme.
     * @type {string}
     * @memberof Category
     */
    image?: string;
}

export function CategoryFromJSON(json: any): Category {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'identifier': !exists(json, 'identifier') ? undefined : json['identifier'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'ordering': !exists(json, 'ordering') ? undefined : json['ordering'],
        'visibility': !exists(json, 'visibility') ? undefined : json['visibility'],
        'lft': !exists(json, 'lft') ? undefined : json['lft'],
        'rght': !exists(json, 'rght') ? undefined : json['rght'],
        'treeId': !exists(json, 'tree_id') ? undefined : json['tree_id'],
        'level': !exists(json, 'level') ? undefined : json['level'],
        'parent': !exists(json, 'parent') ? undefined : json['parent'],
        'image': !exists(json, 'image') ? undefined : json['image'],
    };
}

export function CategoryToJSON(value?: Category): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'status': value.status,
        'ordering': value.ordering,
        'visibility': value.visibility,
        'parent': value.parent,
        'image': value.image,
    };
}


