// tslint:disable
/**
 * OE API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginSeller
 */
export interface LoginSeller  {
    /**
     * 
     * @type {string}
     * @memberof LoginSeller
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof LoginSeller
     */
    password: string;
}

export function LoginSellerFromJSON(json: any): LoginSeller {
    return {
        'email': json['email'],
        'password': json['password'],
    };
}

export function LoginSellerToJSON(value?: LoginSeller): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'email': value.email,
        'password': value.password,
    };
}


