// tslint:disable
/**
 * OE API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SellerBank
 */
export interface SellerBank  {
    /**
     * 
     * @type {number}
     * @memberof SellerBank
     */
    readonly id?: number;
    /**
     * 
     * @type {Date}
     * @memberof SellerBank
     */
    readonly createdOn?: Date;
    /**
     * 
     * @type {Date}
     * @memberof SellerBank
     */
    readonly modifiedOn?: Date;
    /**
     * The name of the bank that should be used
     * @type {string}
     * @memberof SellerBank
     */
    name: string;
    /**
     * You can enter the account number for your bank.
     * @type {string}
     * @memberof SellerBank
     */
    accNumber?: string;
    /**
     * Where the bank is located
     * @type {string}
     * @memberof SellerBank
     */
    location?: string;
}

export function SellerBankFromJSON(json: any): SellerBank {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdOn': !exists(json, 'created_on') ? undefined : new Date(json['created_on']),
        'modifiedOn': !exists(json, 'modified_on') ? undefined : new Date(json['modified_on']),
        'name': json['name'],
        'accNumber': !exists(json, 'acc_number') ? undefined : json['acc_number'],
        'location': !exists(json, 'location') ? undefined : json['location'],
    };
}

export function SellerBankToJSON(value?: SellerBank): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'name': value.name,
        'acc_number': value.accNumber,
        'location': value.location,
    };
}


