// tslint:disable
/**
 * OE API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Address,
    AddressFromJSON,
    AddressToJSON,
    SellerBank,
    SellerBankFromJSON,
    SellerBankToJSON,
    User,
    UserFromJSON,
    UserToJSON,
} from './';

/**
 * 
 * @export
 * @interface SellerCreate
 */
export interface SellerCreate  {
    /**
     * 
     * @type {number}
     * @memberof SellerCreate
     */
    readonly id?: number;
    /**
     * 
     * @type {User}
     * @memberof SellerCreate
     */
    owner: User;
    /**
     * 
     * @type {string}
     * @memberof SellerCreate
     */
    status?: string;
    /**
     * 
     * @type {SellerBank}
     * @memberof SellerCreate
     */
    bank: SellerBank;
    /**
     * 
     * @type {Address}
     * @memberof SellerCreate
     */
    address: Address;
    /**
     * 
     * @type {Date}
     * @memberof SellerCreate
     */
    readonly createdOn?: Date;
    /**
     * 
     * @type {Date}
     * @memberof SellerCreate
     */
    readonly modifiedOn?: Date;
    /**
     * The name of the seller
     * @type {string}
     * @memberof SellerCreate
     */
    name?: string;
    /**
     * The business_name 
     * @type {string}
     * @memberof SellerCreate
     */
    businessName?: string;
    /**
     * You can enter the promary contact phone number.
     * @type {string}
     * @memberof SellerCreate
     */
    phoneNumber?: string;
    /**
     * Seller logo. Will be shown at theme.
     * @type {string}
     * @memberof SellerCreate
     */
    logo?: string;
}

export function SellerCreateFromJSON(json: any): SellerCreate {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'owner': UserFromJSON(json['owner']),
        'status': !exists(json, 'status') ? undefined : json['status'],
        'bank': SellerBankFromJSON(json['bank']),
        'address': AddressFromJSON(json['address']),
        'createdOn': !exists(json, 'created_on') ? undefined : new Date(json['created_on']),
        'modifiedOn': !exists(json, 'modified_on') ? undefined : new Date(json['modified_on']),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'businessName': !exists(json, 'business_name') ? undefined : json['business_name'],
        'phoneNumber': !exists(json, 'phone_number') ? undefined : json['phone_number'],
        'logo': !exists(json, 'logo') ? undefined : json['logo'],
    };
}

export function SellerCreateToJSON(value?: SellerCreate): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'owner': UserToJSON(value.owner),
        'status': value.status,
        'bank': SellerBankToJSON(value.bank),
        'address': AddressToJSON(value.address),
        'name': value.name,
        'business_name': value.businessName,
        'phone_number': value.phoneNumber,
        'logo': value.logo,
    };
}


